defaults:
  - data: scifact
  - _self_

experiment_name: "rq1"
mode: "always_retrieve" # "always_retrieve" | "never_retrieve" | "uq_aware"

retriever:
  type: "vector_db"
  db_path: ${data.db_path}
  collection_name: ${data.collection_name}
  embedding_model: "BAAI/bge-m3"
  top_k: 3
  debug: false

llm:
  provider: "local_huggingface"
  model_name: "Qwen/Qwen2.5-1.5B-Instruct"
  device: "cuda"
  max_new_tokens: 512
  do_sample: False
  debug: false

aggregator:
  max_context_tokens: 8000

prompts:
  rag: ${data.rag_prompt}

  parametric: ${data.parametric_prompt}

uncertainty:
  method: "MeanTokenEntropy"
  threshold: 0.0
  calibration_mode: True