defaults:
  - data: scifact
  - _self_

experiment_name: "rq1"
mode: "always_retrieve" # "always_retrieve" | "never_retrieve" | "uq_aware"

retriever:
  type: "vector_db"
  db_path: ${data.db_path}
  collection_name: ${data.collection_name}
  embedding_model: "BAAI/bge-m3"
  top_k: ${data.top_k}
  debug: False

llm:
  provider: "local_huggingface"
  model_name: "Qwen/Qwen3-4B-Instruct-2507"
  device: "cuda"
  max_new_tokens: 1024
  do_sample: False
  debug: False

aggregator:
  max_context_tokens: ${data.max_context_tokens}

prompts:
  rag: ${data.rag_prompt}

  parametric: ${data.parametric_prompt}

uncertainty:
  method: "MeanTokenEntropy"
  threshold: 0.0
  calibration_mode: True